apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: Employee-Management-System
spec:
  selector:
    matchLabels:
      app: hdfcems-k8s
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: hdfcems-k8s
    spec:
      containers:
        - name: hdfcems-k8s
          image: nehadangat17/employeesystem # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1999 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: hdfcems-k8ssvc
spec:
  selector:
    app: hdfcems-k8s
  ports:
    - protocol: "TCP"
      port: 1999 # The port that the service is running on in the cluster
      targetPort: 1999 # The port exposed by the service
  type: NodePort # type of the service.